### ISSUE TITLE
IMessageFormatter param is not nullable

### ISSUE THREAD

**Issue by onatsko** [dncuug/X.Extensions.Logging.Telegram#37]
I use your lib for sending message to Telegram, it works great, thank you!

But today I enable <WarningsAsErrors>nullable</WarningsAsErrors> in project
and get error on code:
```
   logConfig = logConfig.WriteTo.Telegram(config => { ....  }, null, logLevelError);
```

null is param IMessageFormatter messageFormatter

in ctor I see that it is not nullable
```
    public static LoggerConfiguration Telegram(
      this LoggerSinkConfiguration loggerConfiguration,
      Action<TelegramSinkConfiguration> configureAction,
      IMessageFormatter messageFormatter,
      LogEventLevel restrictedToMinimumLevel = LogEventLevel.Verbose)
```

but in next ctor TelegramSink is nullable
```
    public TelegramSink(
      ChannelWriter<LogEvent> channelWriter,
      ILogsQueueAccessor logsQueueAccessor,
      TelegramSinkConfiguration sinkConfiguration,
      IMessageFormatter? messageFormatter)
```

pls make IMessageFormatter nullable in LoggerConfiguration Telegram

**Comment by a-gubskiy** [comment]
@onatsko please check this version: https://www.nuget.org/packages/X.Extensions.Logging.Telegram/2.0.1-rc

**Comment by onatsko** [comment]
thanx!
